"""
Build content bundles for all courses.

Regenerates the JS bundle files in each course's bundles/ directory
from the current JSON content on disk. Run after authoring content
via edit mode and before deploying to GitHub Pages.

Usage:  cd docs && python build-bundles.py
        python docs/build-bundles.py          (from repo root)
"""

import json
import os
import glob
import sys

DOCS_DIR = os.path.dirname(os.path.abspath(__file__))
COURSES_DIR = os.path.join(DOCS_DIR, "courses")
I18N_DIR = os.path.join(DOCS_DIR, "content", "i18n")

LOCALES = ["en", "fr", "de", "ja", "zh", "ko", "es"]

BUNDLE_HEADER = """\
/**
 * OB -- {label} Content Bundle
 * {underline}
 * All {label} content embedded as JS for file:// compatibility.
 * Auto-generated by build-bundles.py — do not edit manually.
 */
(function () {{
  "use strict";
  var OB = window.OB = window.OB || {{}};

  OB.{var_name} = {{
"""

BUNDLE_FOOTER = """\
  };
})();
"""


def read_json(path):
    """Read and parse a JSON file, returning (data, raw_text)."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def json_indent(data, indent=2):
    """Serialize data with consistent indentation."""
    return json.dumps(data, indent=indent, ensure_ascii=False)


def collect_content_files(course_dir, locale_prefix=""):
    """Collect all content JSON files for a course (or locale subdir).

    Returns a dict of { bundle_key: parsed_json_data }.
    Bundle keys match what loadJSON() uses: "course.json",
    "modules/m1-foo.json", "quizzes/q1-foo.json", "glossary.json".
    """
    base = os.path.join(course_dir, locale_prefix) if locale_prefix else course_dir
    entries = {}

    # course.json
    p = os.path.join(base, "course.json")
    if os.path.isfile(p):
        entries["course.json"] = read_json(p)

    # glossary.json
    p = os.path.join(base, "glossary.json")
    if os.path.isfile(p):
        entries["glossary.json"] = read_json(p)

    # modules/*.json
    modules_dir = os.path.join(base, "modules")
    if os.path.isdir(modules_dir):
        for f in sorted(glob.glob(os.path.join(modules_dir, "*.json"))):
            key = "modules/" + os.path.basename(f)
            entries[key] = read_json(f)

    # quizzes/*.json
    quizzes_dir = os.path.join(base, "quizzes")
    if os.path.isdir(quizzes_dir):
        for f in sorted(glob.glob(os.path.join(quizzes_dir, "*.json"))):
            key = "quizzes/" + os.path.basename(f)
            entries[key] = read_json(f)

    return entries


def build_bundle(course_id, course_dir, locale):
    """Build a single bundle JS file for a course + locale."""
    is_en = locale == "en"
    locale_prefix = "" if is_en else locale

    # Collect course content
    entries = collect_content_files(course_dir, locale_prefix)
    if not entries:
        return None  # No content for this locale

    # Add UI strings
    ui_file = os.path.join(I18N_DIR, f"ui-{locale}.json")
    if os.path.isfile(ui_file):
        entries[f"i18n/ui-{locale}.json"] = read_json(ui_file)

    # Determine JS variable name
    if is_en:
        var_name = "_courseBundle"
        label = ""
    else:
        var_name = "_courseBundle" + locale[0].upper() + locale[1:]
        label = locale.upper() + " "

    # Build output
    underline = "=" * (len(label) + len("Content Bundle") + 8)
    out = BUNDLE_HEADER.format(
        label=label.strip() or "English",
        underline=underline,
        var_name=var_name,
    )

    keys = list(entries.keys())
    for i, key in enumerate(keys):
        data_str = json_indent(entries[key])
        comma = "," if i < len(keys) - 1 else ""
        out += f'    "{key}": {data_str}{comma}\n'

    out += BUNDLE_FOOTER

    return out


def main():
    if not os.path.isdir(COURSES_DIR):
        print(f"Error: courses directory not found: {COURSES_DIR}", file=sys.stderr)
        sys.exit(1)

    total = 0

    for course_id in sorted(os.listdir(COURSES_DIR)):
        course_dir = os.path.join(COURSES_DIR, course_id)
        if not os.path.isdir(course_dir):
            continue

        bundles_dir = os.path.join(course_dir, "bundles")
        if not os.path.isdir(bundles_dir):
            # Only build bundles for courses that already have a bundles/ dir
            continue

        print(f"[{course_id}]")

        for locale in LOCALES:
            content = build_bundle(course_id, course_dir, locale)
            if not content:
                continue

            out_path = os.path.join(bundles_dir, f"{locale}.js")
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(content)

            size_kb = len(content.encode("utf-8")) / 1024
            print(f"  {locale}.js  ({size_kb:.0f} KB)")
            total += 1

    print(f"\nDone — {total} bundles written.")


if __name__ == "__main__":
    main()
