"""
Export subsets of the training catalog as standalone PWAs.

Packages a filtered subset of courses (by product family or individual
course IDs) into a self-contained directory with service worker and
manifest.json for offline/installable use.

Usage:
  cd docs && python export-standalone.py --family windchill --output ../dist/windchill/
  cd docs && python export-standalone.py --course wc-ocp1 --output ../dist/ocp1/
  cd docs && python export-standalone.py --course wc-ocp1,cb-overview --output ../dist/custom/
  cd docs && python export-standalone.py --all --output ../dist/full/
"""

import argparse
import json
import os
import shutil
import sys

DOCS_DIR = os.path.dirname(os.path.abspath(__file__))
COURSES_DIR = os.path.join(DOCS_DIR, "courses")
I18N_DIR = os.path.join(DOCS_DIR, "content", "i18n")

# Files/dirs to copy from docs/ into the export
CSS_FILES = [
    "css/variables.css",
    "css/base.css",
    "css/sidebar.css",
    "css/components.css",
    "css/views.css",
    "css/animations.css",
]

JS_FILES = [
    "js/ui.js",
    "js/state.js",
    "js/catalog-bundle.js",
    "js/content.js",
    "js/i18n.js",
    "js/theme.js",
    "js/sidebar.js",
    "js/dashboard.js",
    "js/topic.js",
    "js/quiz.js",
    "js/glossary.js",
    "js/notepad.js",
    "js/speech.js",
    "js/author.js",
    "js/export.js",
    "js/router.js",
]

I18N_FILES = [
    "content/i18n/ui-en.json",
    "content/i18n/ui-fr.json",
    "content/i18n/ui-de.json",
    "content/i18n/ui-ja.json",
    "content/i18n/ui-zh.json",
    "content/i18n/ui-ko.json",
    "content/i18n/ui-es.json",
]


def load_catalog():
    """Load the full catalog.json."""
    path = os.path.join(DOCS_DIR, "catalog.json")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_catalog_bundle():
    """Load the catalog-bundle.js to extract the existing UI strings."""
    path = os.path.join(DOCS_DIR, "js", "catalog-bundle.js")
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def filter_catalog(catalog, family_ids=None, course_ids=None):
    """Filter catalog to only include selected families/courses.

    Returns (filtered_catalog, list_of_course_ids).
    """
    filtered_families = []
    selected_course_ids = []

    for fam in catalog["families"]:
        if family_ids and fam["id"] not in family_ids:
            # Check if any individual courses from this family were requested
            if not course_ids:
                continue
            matching = [c for c in fam["courses"] if c["id"] in course_ids]
            if not matching:
                continue
            filtered_fam = dict(fam)
            filtered_fam["courses"] = matching
            filtered_families.append(filtered_fam)
            selected_course_ids.extend(c["id"] for c in matching)
        elif family_ids:
            # Include entire family
            filtered_families.append(fam)
            selected_course_ids.extend(c["id"] for c in fam["courses"])
        elif course_ids:
            # Filter by course IDs within this family
            matching = [c for c in fam["courses"] if c["id"] in course_ids]
            if matching:
                filtered_fam = dict(fam)
                filtered_fam["courses"] = matching
                filtered_families.append(filtered_fam)
                selected_course_ids.extend(c["id"] for c in matching)

    filtered = dict(catalog)
    filtered["families"] = filtered_families
    return filtered, selected_course_ids


def generate_catalog_bundle(filtered_catalog, ui_strings_src):
    """Generate a catalog-bundle.js with filtered catalog data.

    Reuses the UI strings from the original bundle.
    """
    # Extract the UI strings block from the original bundle
    # Find OB._uiStringsEn = { ... };
    ui_start = ui_strings_src.find("OB._uiStringsEn = {")
    if ui_start == -1:
        ui_start = ui_strings_src.find("OB._uiStringsEn={")
    # Find the matching closing };
    brace_count = 0
    ui_end = ui_start
    for i in range(ui_start, len(ui_strings_src)):
        if ui_strings_src[i] == "{":
            brace_count += 1
        elif ui_strings_src[i] == "}":
            brace_count -= 1
            if brace_count == 0:
                ui_end = i + 1
                break

    # Find the end of the statement (the semicolon)
    semi = ui_strings_src.find(";", ui_end)
    ui_block = ui_strings_src[ui_start : semi + 1]

    catalog_json = json.dumps(filtered_catalog, indent=1, ensure_ascii=False)

    return f"""\
/**
 * OB -- Catalog Bundle
 * =====================
 * Catalog data embedded as JS for file:// compatibility.
 * Generated by export-standalone.py
 */
(function () {{
 "use strict";
 var OB = window.OB = window.OB || {{}};

 {ui_block}

 OB._catalogBundle = {catalog_json};
}})();
"""


def generate_manifest(app_name, short_name):
    """Generate a manifest.json for PWA install."""
    return json.dumps(
        {
            "name": app_name,
            "short_name": short_name,
            "start_url": ".",
            "display": "standalone",
            "background_color": "#1a1a2e",
            "theme_color": "#3b82f6",
            "icons": [],
        },
        indent=2,
        ensure_ascii=False,
    )


def generate_service_worker(precache_files):
    """Generate a service-worker.js that precaches all files."""
    files_json = json.dumps(precache_files, indent=2, ensure_ascii=False)
    return f"""\
// Service Worker for PTC Training PWA
// Generated by export-standalone.py
const CACHE_NAME = 'ptc-training-v1';

const PRECACHE_FILES = {files_json};

self.addEventListener('install', event => {{
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(PRECACHE_FILES))
  );
  self.skipWaiting();
}});

self.addEventListener('activate', event => {{
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
}});

self.addEventListener('fetch', event => {{
  event.respondWith(
    caches.match(event.request).then(cached => cached || fetch(event.request))
  );
}});
"""


def patch_index_html(html):
    """Patch index.html to add manifest link and service worker registration."""
    # Add manifest link in <head>
    manifest_link = '  <link rel="manifest" href="manifest.json">\n'
    html = html.replace("</head>", manifest_link + "</head>")

    # Add SW registration before closing </body>
    sw_script = """\
  <script>
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('service-worker.js').catch(function() {});
    }
  </script>
"""
    html = html.replace("</body>", sw_script + "</body>")

    return html


def collect_precache_files(output_dir):
    """Walk the output directory and collect all file paths relative to root."""
    files = []
    for root, _dirs, filenames in os.walk(output_dir):
        for fname in filenames:
            full = os.path.join(root, fname)
            rel = os.path.relpath(full, output_dir).replace("\\", "/")
            files.append(rel)
    files.sort()
    # Add the root URL
    if "." not in files:
        files.insert(0, ".")
    return files


def copy_file(src, dst):
    """Copy a file, creating parent directories as needed."""
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst)


def copy_course(course_id, output_dir):
    """Copy a course's bundles and images to the output directory."""
    src_dir = os.path.join(COURSES_DIR, course_id)
    dst_dir = os.path.join(output_dir, "courses", course_id)

    if not os.path.isdir(src_dir):
        print(f"  Warning: course directory not found: {course_id}")
        return

    # Copy bundles/
    bundles_src = os.path.join(src_dir, "bundles")
    if os.path.isdir(bundles_src):
        bundles_dst = os.path.join(dst_dir, "bundles")
        os.makedirs(bundles_dst, exist_ok=True)
        for f in os.listdir(bundles_src):
            if f.endswith(".js"):
                copy_file(os.path.join(bundles_src, f), os.path.join(bundles_dst, f))

    # Copy images/
    images_src = os.path.join(src_dir, "images")
    if os.path.isdir(images_src):
        images_dst = os.path.join(dst_dir, "images")
        os.makedirs(images_dst, exist_ok=True)
        for f in os.listdir(images_src):
            copy_file(os.path.join(images_src, f), os.path.join(images_dst, f))


def derive_names(catalog, family_ids, course_ids):
    """Derive app name and short name from the selection."""
    if family_ids:
        names = []
        for fam in catalog["families"]:
            if fam["id"] in family_ids:
                names.append(fam["name"])
        label = ", ".join(names)
        return f"PTC Training: {label}", f"{label} Training"

    if course_ids and len(course_ids) == 1:
        for fam in catalog["families"]:
            for c in fam["courses"]:
                if c["id"] == course_ids[0]:
                    return f"PTC Training: {c['title']}", c["title"]

    return "PTC Training", "PTC Training"


def main():
    parser = argparse.ArgumentParser(
        description="Export training catalog subsets as standalone PWAs"
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--family",
        help="Product family ID(s) to export (comma-separated)",
    )
    group.add_argument(
        "--course",
        help="Course ID(s) to export (comma-separated)",
    )
    group.add_argument(
        "--all",
        action="store_true",
        help="Export all courses",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output directory for the standalone app",
    )

    args = parser.parse_args()

    # Parse selection
    family_ids = None
    course_ids = None
    if args.family:
        family_ids = [f.strip() for f in args.family.split(",")]
    elif args.course:
        course_ids = [c.strip() for c in args.course.split(",")]

    # Load source data
    catalog = load_catalog()
    catalog_bundle_src = load_catalog_bundle()

    # Filter catalog
    if args.all:
        filtered_catalog = catalog
        selected_ids = []
        for fam in catalog["families"]:
            selected_ids.extend(c["id"] for c in fam["courses"])
    else:
        filtered_catalog, selected_ids = filter_catalog(
            catalog, family_ids, course_ids
        )

    if not filtered_catalog["families"]:
        print("Error: no matching families/courses found.", file=sys.stderr)
        sys.exit(1)

    # Derive names
    app_name, short_name = derive_names(catalog, family_ids, course_ids)

    output_dir = os.path.abspath(args.output)
    print(f"Exporting: {app_name}")
    print(f"Courses: {', '.join(selected_ids)}")
    print(f"Output: {output_dir}")
    print()

    # Clean output directory
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    os.makedirs(output_dir)

    # 1. Copy and patch index.html
    print("  index.html (patched)")
    src_html = os.path.join(DOCS_DIR, "index.html")
    with open(src_html, "r", encoding="utf-8") as f:
        html = f.read()
    html = patch_index_html(html)
    with open(os.path.join(output_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

    # 2. Copy CSS files
    for rel in CSS_FILES:
        src = os.path.join(DOCS_DIR, rel)
        dst = os.path.join(output_dir, rel)
        if os.path.isfile(src):
            copy_file(src, dst)
            print(f"  {rel}")

    # 3. Copy JS files (except catalog-bundle.js which we regenerate)
    for rel in JS_FILES:
        if rel == "js/catalog-bundle.js":
            continue  # Generated below
        src = os.path.join(DOCS_DIR, rel)
        dst = os.path.join(output_dir, rel)
        if os.path.isfile(src):
            copy_file(src, dst)
            print(f"  {rel}")

    # 4. Generate filtered catalog-bundle.js
    print("  js/catalog-bundle.js (generated)")
    bundle_js = generate_catalog_bundle(filtered_catalog, catalog_bundle_src)
    bundle_path = os.path.join(output_dir, "js", "catalog-bundle.js")
    os.makedirs(os.path.dirname(bundle_path), exist_ok=True)
    with open(bundle_path, "w", encoding="utf-8") as f:
        f.write(bundle_js)

    # 5. Copy i18n files
    for rel in I18N_FILES:
        src = os.path.join(DOCS_DIR, rel)
        dst = os.path.join(output_dir, rel)
        if os.path.isfile(src):
            copy_file(src, dst)
            print(f"  {rel}")

    # 6. Copy course content (bundles + images)
    for course_id in selected_ids:
        print(f"  courses/{course_id}/")
        copy_course(course_id, output_dir)

    # 7. Generate manifest.json
    print("  manifest.json (generated)")
    manifest = generate_manifest(app_name, short_name)
    with open(os.path.join(output_dir, "manifest.json"), "w", encoding="utf-8") as f:
        f.write(manifest)

    # 8. Generate service-worker.js (needs full file list, so do this last)
    precache = collect_precache_files(output_dir)
    print(f"  service-worker.js (generated, {len(precache)} files)")
    sw = generate_service_worker(precache)
    with open(
        os.path.join(output_dir, "service-worker.js"), "w", encoding="utf-8"
    ) as f:
        f.write(sw)

    # Summary
    total_size = 0
    file_count = 0
    for root, _dirs, filenames in os.walk(output_dir):
        for fname in filenames:
            total_size += os.path.getsize(os.path.join(root, fname))
            file_count += 1

    print(f"\nDone — {file_count} files, {total_size / 1024 / 1024:.1f} MB total.")
    print(f"\nTo test:\n  cd {output_dir} && python -m http.server 8051")


if __name__ == "__main__":
    main()
